# Generated by Django 3.2.25 on 2024-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fullname',
        ),
    ]
